---
# An example of basic hosts-file configuration where first node hosts orderer
all:
  hosts: # localhost connection parameters, used for storing configuration while transferring it between nodes
    localhost:
      ansible_connection: local
  vars:
    domain: example.com
    orderer_type: solo
  children:
    nodes:
      hosts:
        orderer.example.com:
          node_roles: # Describes which containers will run on this node
            - root_orderer
            - orderer
            - peer
            - root_peer
            - explorer
          org: mainorg # Organization name
          ansible_host: 1.2.3.4 # Real ip address or domain name of the machine
          ansible_user: ubuntu # User with sudo access
          ansible_private_key_file: ~/test.pem # Private key to identify ourselves
        # Same structure for any other nodes
        one.example.com:
          node_roles:
            - peer
          org: one
          ansible_host: 1.2.3.5
          ansible_user: ubuntu
          ansible_private_key_file: ~/test.pem
        two.example.com:
          node_roles:
            - peer
          org: two
          ansible_host: 1.2.3.6
          ansible_user: ubuntu
          ansible_private_key_file: ~/test.pem
